#!/usr/bin/python3
import sys

sys.path.extend(['..', '../protos/pythonpb2'])

from client.desk_wol_client import PowerClient

if __name__ == '__main__':
    power_client = PowerClient()
    power_client.exec()
