version: "3"
services:
  server:
    image: yoangau/raspberry-grpc-wol:tagname
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - 50051:50051
    command: /bin/sh -c "pacman -Syu base-devel python3 python-pip --noconfirm && /bin/sh setup.sh && cd ./server && /bin/python3 server"
  repeater:
    image: archlinux/base
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
    command: /bin/sh -c "pacman -Syu base-devel python3 python-pip --noconfirm && /bin/sh setup.sh && cd ./server && /bin/python3 gpio_interface.py"
