#!/usr/bin/python3
import sys

sys.path.extend(['..', '../protos/pythonpb2'])

import logging

from server.desk_wol_server import PowerService

if __name__ == '__main__':
    logging.basicConfig()
    PowerService.serve()
