#!/usr/bin/python3
import os
import sys

# Todo: Dockerimage could be rebuild to add the right PYTHONPATH env var instead of this:
sys.path.extend([os.environ['SERVERPATH'], f"{os.environ['SERVERPATH']}/protos/pythonpb2"])

import logging

from server.desk_wol_server import PowerService

if __name__ == '__main__':
    logging.basicConfig()
    PowerService.serve()
